services:
  nextjs:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      server:
        condition: service_healthy

  server:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/db/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: ["-path", "/migrations/", "-database", "postgres://zhaozhenghao:zhaozhenghao@db:5432/postgres?sslmode=disable", "up"]

  db:
    image: postgres
    env_file:
      - ./backend/.env
    ports:
      - 5434:5432 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 3s
      retries: 3 

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
